swagger: "2.0"
info:
  title: Email Service API
  description: This API is responsible for sending emails.
  version: 1.0.0
basePath: /api/v1
schemes:
  - https
paths:
  /emails:
    post:
      summary: Sends a new email
      description: Endpoint used to send new emails
      consumes:
       - multipart/form-data
      parameters:
        - name: subject
          in: formData
          description: Email Subject
          required: false
          type: string
        - name: to
          in: formData
          description: Email TO
          required: true
          type: array
          items:
            type: string
        - name: cc
          in: formData
          description: Email CC
          required: false
          type: array
          items:
            type: string
        - name: bcc
          in: formData
          description: Email BCC
          required: false
          type: array
          items:
            type: string
        - name: body
          in: formData
          description: Email Body
          required: false
          type: string
        - name: attachments
          in: formData
          description: Upload multiple files
          required: false
          type: array
          items:
            type: string
            format: binary
      responses:
        200:
          description: 'OK: Email was sent sucessfully'
        400:
          description: 'BAD_REQUEST: One or more destination addresses are incorrect'
        500:
          description: 'INTERNAL_ERROR: Unknown error occured'
definitions:
  Mail:
    type: object
    properties:
      subject:
          description: Email Subject
          type: string
      from:
          description: Email From
          type: string
      to:
          description: Email TO
          type: array
          items:
            type: string
      cc:
          description: Email CC
          type: array
          items:
            type: string
      bcc:
          description: Email BCC
          type: array
          items:
            type: string
      body:
          description: Email Body
          type: string
      attachments:
          description: Upload multiple files
          type: array
          items:
            type: string
            format: binary
    # Both properties are required
    required:  
      - to